name: base
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - copc-lib
  - fire
  - laspy
  - lazrs-python
  - mkl=2024.0
  - numpy
  - omegaconf
  - pyg
  - python=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchmetrics
  # dev
  - black
  - ipykernel
  - isort
  - pre-commit
  - pylint
  - pip:
      - --prefer-binary --find-links=/wheels
      - MinkowskiEngine # installs a non-cuda PyPI version if used outside the docker
